const adressesP2 =[
  {
    "type": "voie",
    "code_type_voie": 3,
    "type_voie": "lieu-dit",
    "code_commune": 75102,
    "code_rivoli": "P003",
    "cle_rivoli": "Z",
    "libelle_voie": "METRO BONNE NOUVELLE 7",
    "voie_privee": false,
    "code_majic": "00001",
    "mot_directeur": "NOUVELLE",
    "date_ajout": "2001-09-14",
    "id": "75102-P003",
    "libelle_voie_complet": "METRO BONNE NOUVELLE 7",
    "lieu_dit_bati": false
  },
  {
    "type": "voie",
    "code_type_voie": 3,
    "type_voie": "lieu-dit",
    "code_commune": 75102,
    "code_rivoli": "P004",
    "cle_rivoli": "A",
    "libelle_voie": "METRO BONNE NOUVELLE 8",
    "voie_privee": false,
    "code_majic": "00002",
    "mot_directeur": "NOUVELLE",
    "date_ajout": "2001-09-14",
    "id": "75102-P004",
    "libelle_voie_complet": "METRO BONNE NOUVELLE 8",
    "lieu_dit_bati": false
  },
  {
    "type": "voie",
    "code_type_voie": 3,
    "type_voie": "lieu-dit",
    "code_commune": 75102,
    "code_rivoli": "S052",
    "cle_rivoli": "B",
    "libelle_voie": "METRO BOURSE",
    "voie_privee": false,
    "code_majic": "00003",
    "mot_directeur": "BOURSE",
    "date_ajout": "2001-09-14",
    "id": "75102-S052",
    "libelle_voie_complet": "METRO BOURSE",
    "lieu_dit_bati": true
  },
  {
    "type": "voie",
    "code_type_voie": 3,
    "type_voie": "lieu-dit",
    "code_commune": 75102,
    "code_rivoli": "S337",
    "cle_rivoli": "L",
    "libelle_voie": "METRO MONTMARTRE",
    "voie_privee": false,
    "code_majic": "00004",
    "mot_directeur": "MONTMART",
    "date_ajout": "2001-09-14",
    "id": "75102-S337",
    "libelle_voie_complet": "METRO MONTMARTRE",
    "lieu_dit_bati": false
  },
  {
    "type": "voie",
    "code_type_voie": 3,
    "type_voie": "lieu-dit",
    "code_commune": 75102,
    "code_rivoli": "S473",
    "cle_rivoli": "J",
    "libelle_voie": "METRO QUATRE SEPTEMBRE",
    "voie_privee": false,
    "code_majic": "00005",
    "mot_directeur": "SEPTEMBR",
    "date_ajout": "2001-09-14",
    "id": "75102-S473",
    "libelle_voie_complet": "METRO QUATRE SEPTEMBRE",
    "lieu_dit_bati": true
  },
  {
    "type": "voie",
    "code_type_voie": 3,
    "type_voie": "lieu-dit",
    "code_commune": 75102,
    "code_rivoli": "S484",
    "cle_rivoli": "W",
    "libelle_voie": "METRO REAUMUR SEBASTOPOL",
    "voie_privee": false,
    "code_majic": "00006",
    "mot_directeur": "SEBASTOP",
    "date_ajout": "2001-09-14",
    "id": "75102-S484",
    "libelle_voie_complet": "METRO REAUMUR SEBASTOPOL",
    "lieu_dit_bati": false
  },
  {
    "type": "voie",
    "code_type_voie": 3,
    "type_voie": "lieu-dit",
    "code_commune": 75102,
    "code_rivoli": "S531",
    "cle_rivoli": "X",
    "libelle_voie": "METRO SENTIER",
    "voie_privee": false,
    "code_majic": "00007",
    "mot_directeur": "SENTIER",
    "date_ajout": "2001-09-14",
    "id": "75102-S531",
    "libelle_voie_complet": "METRO SENTIER",
    "lieu_dit_bati": false
  },
  {
    "type": "voie",
    "code_type_voie": 3,
    "type_voie": "lieu-dit",
    "code_commune": 75102,
    "code_rivoli": "S537",
    "cle_rivoli": "D",
    "libelle_voie": "METRO STRASBOURG ST DENIS",
    "voie_privee": false,
    "code_majic": "00008",
    "mot_directeur": "DENIS",
    "date_ajout": "2001-09-14",
    "id": "75102-S537",
    "libelle_voie_complet": "METRO STRASBOURG ST DENIS",
    "lieu_dit_bati": false
  },
  {
    "type": "voie",
    "code_type_voie": 3,
    "type_voie": "lieu-dit",
    "code_commune": 75102,
    "code_rivoli": "S659",
    "cle_rivoli": "L",
    "libelle_voie": "S S STA SEBASTOPOL",
    "voie_privee": false,
    "code_majic": "00009",
    "mot_directeur": "SEBASTOP",
    "date_ajout": "2001-09-14",
    "id": "75102-S659",
    "libelle_voie_complet": "S S STA SEBASTOPOL",
    "lieu_dit_bati": false
  },
  {
    "type": "voie",
    "code_type_voie": 3,
    "type_voie": "lieu-dit",
    "code_commune": 75102,
    "code_rivoli": "S660",
    "cle_rivoli": "M",
    "libelle_voie": "S S STA SENTIER",
    "voie_privee": false,
    "code_majic": "00010",
    "mot_directeur": "SENTIER",
    "date_ajout": "2001-09-14",
    "id": "75102-S660",
    "libelle_voie_complet": "S S STA SENTIER",
    "lieu_dit_bati": false
  },
  {
    "type": "voie",
    "code_type_voie": 4,
    "type_voie": "pseudo-voie",
    "code_commune": 75102,
    "code_rivoli": "X013",
    "cle_rivoli": "U",
    "libelle_voie": "A 2",
    "voie_privee": false,
    "code_majic": "00162",
    "mot_directeur": 2,
    "date_ajout": "2001-09-14",
    "id": "75102-X013",
    "libelle_voie_complet": "PASSAGE A 2",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": "0040",
    "cle_rivoli": "P",
    "libelle_voie": "D ABOUKIR",
    "voie_privee": false,
    "code_majic": "00012",
    "mot_directeur": "ABOUKIR",
    "date_ajout": "2001-09-14",
    "id": "75102-0040",
    "libelle_voie_complet": "RUE D ABOUKIR",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": "0166",
    "cle_rivoli": "B",
    "libelle_voie": "D ALEXANDRIE",
    "voie_privee": false,
    "code_majic": "00013",
    "mot_directeur": "ALEXANDR",
    "date_ajout": "2001-09-14",
    "id": "75102-0166",
    "libelle_voie_complet": "RUE D ALEXANDRIE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": "0260",
    "cle_rivoli": "D",
    "libelle_voie": "D AMBOISE",
    "voie_privee": false,
    "code_majic": "00014",
    "mot_directeur": "AMBOISE",
    "date_ajout": "2001-09-14",
    "id": "75102-0260",
    "libelle_voie_complet": "RUE D AMBOISE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": "0366",
    "cle_rivoli": "U",
    "libelle_voie": "D ANTIN",
    "voie_privee": false,
    "code_majic": "00015",
    "mot_directeur": "ANTIN",
    "date_ajout": "2001-09-14",
    "id": "75102-0366",
    "libelle_voie_complet": "RUE D ANTIN",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": "0440",
    "cle_rivoli": "Z",
    "libelle_voie": "D ARGOUT",
    "voie_privee": false,
    "code_majic": "00016",
    "mot_directeur": "ARGOUT",
    "date_ajout": "2001-09-14",
    "id": "75102-0440",
    "libelle_voie_complet": "RUE D ARGOUT",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": "0622",
    "cle_rivoli": "X",
    "libelle_voie": "BACHAUMONT",
    "voie_privee": false,
    "code_majic": "00017",
    "mot_directeur": "BACHAUMO",
    "date_ajout": "2001-09-14",
    "id": "75102-0622",
    "libelle_voie_complet": "RUE BACHAUMONT",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": "0654",
    "cle_rivoli": "G",
    "libelle_voie": "DE LA BANQUE",
    "voie_privee": false,
    "code_majic": "00018",
    "mot_directeur": "BANQUE",
    "date_ajout": "2001-09-14",
    "id": "75102-0654",
    "libelle_voie_complet": "RUE DE LA BANQUE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": "0698",
    "cle_rivoli": "E",
    "libelle_voie": "BASFOUR",
    "voie_privee": false,
    "code_majic": "00019",
    "mot_directeur": "BASFOUR",
    "date_ajout": "2001-09-14",
    "id": "75102-0698",
    "libelle_voie_complet": "PASSAGE BASFOUR",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": "0789",
    "cle_rivoli": "D",
    "libelle_voie": "BEAUREGARD",
    "voie_privee": false,
    "code_majic": "00020",
    "mot_directeur": "BEAUREGA",
    "date_ajout": "2001-09-14",
    "id": "75102-0789",
    "libelle_voie_complet": "RUE BEAUREGARD",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": "0791",
    "cle_rivoli": "F",
    "libelle_voie": "BEAUREPAIRE",
    "voie_privee": false,
    "code_majic": "00021",
    "mot_directeur": "BEAUREPA",
    "date_ajout": "2001-09-14",
    "id": "75102-0791",
    "libelle_voie_complet": "CITE BEAUREPAIRE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": "0855",
    "cle_rivoli": "A",
    "libelle_voie": "BEN-AIAD",
    "voie_privee": false,
    "code_majic": "00022",
    "mot_directeur": "AIAD",
    "date_ajout": "2001-09-14",
    "id": "75102-0855",
    "libelle_voie_complet": "PASSAGE BEN AIAD",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 1021,
    "cle_rivoli": "F",
    "libelle_voie": "BLONDEL",
    "voie_privee": false,
    "code_majic": "00023",
    "mot_directeur": "BLONDEL",
    "date_ajout": "2001-09-14",
    "id": "75102-1021",
    "libelle_voie_complet": "RUE BLONDEL",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 1055,
    "cle_rivoli": "T",
    "libelle_voie": "BOIELDIEU",
    "voie_privee": false,
    "code_majic": "00024",
    "mot_directeur": "BOIELDIE",
    "date_ajout": "2001-09-14",
    "id": "75102-1055",
    "libelle_voie_complet": "PLACE BOIELDIEU",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 1097,
    "cle_rivoli": "N",
    "libelle_voie": "DE BONNE NOUVELLE",
    "voie_privee": false,
    "code_majic": "00025",
    "mot_directeur": "NOUVELLE",
    "date_ajout": "2001-09-14",
    "id": "75102-1097",
    "libelle_voie_complet": "BOULEVARD DE BONNE NOUVELLE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 1199,
    "cle_rivoli": "Z",
    "libelle_voie": "DU BOURG L ABBE",
    "voie_privee": false,
    "code_majic": "00026",
    "mot_directeur": "ABBE",
    "date_ajout": "2001-09-14",
    "id": "75102-1199",
    "libelle_voie_complet": "PASSAGE DU BOURG L ABBE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 1215,
    "cle_rivoli": "S",
    "libelle_voie": "PALAIS DE LA BOURSE",
    "voie_privee": false,
    "code_majic": "00027",
    "mot_directeur": "BOURSE",
    "date_ajout": "2001-09-14",
    "id": "75102-1215",
    "libelle_voie_complet": "PALAIS DE LA BOURSE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 1216,
    "cle_rivoli": "T",
    "libelle_voie": "DE LA BOURSE",
    "voie_privee": false,
    "code_majic": "00028",
    "mot_directeur": "BOURSE",
    "date_ajout": "2001-09-14",
    "id": "75102-1216",
    "libelle_voie_complet": "PLACE DE LA BOURSE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 1217,
    "cle_rivoli": "U",
    "libelle_voie": "DE LA BOURSE",
    "voie_privee": false,
    "code_majic": "00029",
    "mot_directeur": "BOURSE",
    "date_ajout": "2001-09-14",
    "id": "75102-1217",
    "libelle_voie_complet": "RUE DE LA BOURSE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 1317,
    "cle_rivoli": "C",
    "libelle_voie": "BRONGNIART",
    "voie_privee": false,
    "code_majic": "00030",
    "mot_directeur": "BRONGNIA",
    "date_ajout": "2001-09-14",
    "id": "75102-1317",
    "libelle_voie_complet": "RUE BRONGNIART",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 1429,
    "cle_rivoli": "Z",
    "libelle_voie": "DU CAIRE",
    "voie_privee": false,
    "code_majic": "00031",
    "mot_directeur": "CAIRE",
    "date_ajout": "2001-09-14",
    "id": "75102-1429",
    "libelle_voie_complet": "GALERIE DU CAIRE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 1430,
    "cle_rivoli": "A",
    "libelle_voie": "DU CAIRE",
    "voie_privee": false,
    "code_majic": "00032",
    "mot_directeur": "CAIRE",
    "date_ajout": "2001-09-14",
    "id": "75102-1430",
    "libelle_voie_complet": "PASSAGE DU CAIRE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 1431,
    "cle_rivoli": "B",
    "libelle_voie": "DU CAIRE",
    "voie_privee": false,
    "code_majic": "00033",
    "mot_directeur": "CAIRE",
    "date_ajout": "2001-09-14",
    "id": "75102-1431",
    "libelle_voie_complet": "PLACE DU CAIRE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 1432,
    "cle_rivoli": "C",
    "libelle_voie": "DU CAIRE",
    "voie_privee": false,
    "code_majic": "00034",
    "mot_directeur": "CAIRE",
    "date_ajout": "2001-09-14",
    "id": "75102-1432",
    "libelle_voie_complet": "RUE DU CAIRE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 1524,
    "cle_rivoli": "C",
    "libelle_voie": "DES CAPUCINES",
    "voie_privee": false,
    "code_majic": "00035",
    "mot_directeur": "CAPUCINE",
    "date_ajout": "2001-09-14",
    "id": "75102-1524",
    "libelle_voie_complet": "BOULEVARD DES CAPUCINES",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 1525,
    "cle_rivoli": "D",
    "libelle_voie": "DES CAPUCINES",
    "voie_privee": false,
    "code_majic": "00036",
    "mot_directeur": "CAPUCINE",
    "date_ajout": "2001-09-14",
    "id": "75102-1525",
    "libelle_voie_complet": "RUE DES CAPUCINES",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 1669,
    "cle_rivoli": "K",
    "libelle_voie": "CHABANAIS",
    "voie_privee": false,
    "code_majic": "00037",
    "mot_directeur": "CHABANAI",
    "date_ajout": "2001-09-14",
    "id": "75102-1669",
    "libelle_voie_complet": "RUE CHABANAIS",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 1970,
    "cle_rivoli": "M",
    "libelle_voie": "CHENIER",
    "voie_privee": false,
    "code_majic": "00038",
    "mot_directeur": "CHENIER",
    "date_ajout": "2001-09-14",
    "id": "75102-1970",
    "libelle_voie_complet": "RUE CHENIER",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 1986,
    "cle_rivoli": "E",
    "libelle_voie": "CHERUBINI",
    "voie_privee": false,
    "code_majic": "00039",
    "mot_directeur": "CHERUBIN",
    "date_ajout": "2001-09-14",
    "id": "75102-1986",
    "libelle_voie_complet": "RUE CHERUBINI",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 2012,
    "cle_rivoli": "H",
    "libelle_voie": "CHOISEUL",
    "voie_privee": false,
    "code_majic": "00040",
    "mot_directeur": "CHOISEUL",
    "date_ajout": "2001-09-14",
    "id": "75102-2012",
    "libelle_voie_complet": "PASSAGE CHOISEUL",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 2013,
    "cle_rivoli": "J",
    "libelle_voie": "DE CHOISEUL",
    "voie_privee": false,
    "code_majic": "00041",
    "mot_directeur": "CHOISEUL",
    "date_ajout": "2001-09-14",
    "id": "75102-2013",
    "libelle_voie_complet": "RUE DE CHOISEUL",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 2109,
    "cle_rivoli": "N",
    "libelle_voie": "DE CLERY",
    "voie_privee": false,
    "code_majic": "00042",
    "mot_directeur": "CLERY",
    "date_ajout": "2001-09-14",
    "id": "75102-2109",
    "libelle_voie_complet": "PASSAGE DE CLERY",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 2110,
    "cle_rivoli": "P",
    "libelle_voie": "DE CLERY",
    "voie_privee": false,
    "code_majic": "00043",
    "mot_directeur": "CLERY",
    "date_ajout": "2001-09-14",
    "id": "75102-2110",
    "libelle_voie_complet": "RUE DE CLERY",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 2181,
    "cle_rivoli": "S",
    "libelle_voie": "COLBERT",
    "voie_privee": false,
    "code_majic": "00044",
    "mot_directeur": "COLBERT",
    "date_ajout": "2001-09-14",
    "id": "75102-2181",
    "libelle_voie_complet": "GALERIE COLBERT",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 2182,
    "cle_rivoli": "T",
    "libelle_voie": "COLBERT",
    "voie_privee": false,
    "code_majic": "00045",
    "mot_directeur": "COLBERT",
    "date_ajout": "2001-09-14",
    "id": "75102-2182",
    "libelle_voie_complet": "PASSAGE COLBERT",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 2183,
    "cle_rivoli": "U",
    "libelle_voie": "COLBERT",
    "voie_privee": false,
    "code_majic": "00046",
    "mot_directeur": "COLBERT",
    "date_ajout": "2001-09-14",
    "id": "75102-2183",
    "libelle_voie_complet": "RUE COLBERT",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 2219,
    "cle_rivoli": "H",
    "libelle_voie": "DES COLONNES",
    "voie_privee": false,
    "code_majic": "00047",
    "mot_directeur": "COLONNES",
    "date_ajout": "2001-09-14",
    "id": "75102-2219",
    "libelle_voie_complet": "RUE DES COLONNES",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 2451,
    "cle_rivoli": "K",
    "libelle_voie": "DU CROISSANT",
    "voie_privee": false,
    "code_majic": "00048",
    "mot_directeur": "CROISSAN",
    "date_ajout": "2001-09-14",
    "id": "75102-2451",
    "libelle_voie_complet": "RUE DU CROISSANT",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 2517,
    "cle_rivoli": "G",
    "libelle_voie": "DALAYRAC",
    "voie_privee": false,
    "code_majic": "00049",
    "mot_directeur": "DALAYRAC",
    "date_ajout": "2001-09-14",
    "id": "75102-2517",
    "libelle_voie_complet": "RUE DALAYRAC",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 2528,
    "cle_rivoli": "U",
    "libelle_voie": "DE DAMIETTE",
    "voie_privee": false,
    "code_majic": "00050",
    "mot_directeur": "DAMIETTE",
    "date_ajout": "2001-09-14",
    "id": "75102-2528",
    "libelle_voie_complet": "RUE DE DAMIETTE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 2543,
    "cle_rivoli": "K",
    "libelle_voie": "DANIELLE CASANOVA",
    "voie_privee": false,
    "code_majic": "00051",
    "mot_directeur": "CASANOVA",
    "date_ajout": "2001-09-14",
    "id": "75102-2543",
    "libelle_voie_complet": "RUE DANIELLE CASANOVA",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 2591,
    "cle_rivoli": "M",
    "libelle_voie": "DAUNOU",
    "voie_privee": false,
    "code_majic": "00052",
    "mot_directeur": "DAUNOU",
    "date_ajout": "2001-09-14",
    "id": "75102-2591",
    "libelle_voie_complet": "RUE DAUNOU",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 2645,
    "cle_rivoli": "W",
    "libelle_voie": "DES DEGRES",
    "voie_privee": false,
    "code_majic": "00053",
    "mot_directeur": "DEGRES",
    "date_ajout": "2001-09-14",
    "id": "75102-2645",
    "libelle_voie_complet": "RUE DES DEGRES",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 3055,
    "cle_rivoli": "S",
    "libelle_voie": "DUSSOUBS",
    "voie_privee": false,
    "code_majic": "00054",
    "mot_directeur": "DUSSOUBS",
    "date_ajout": "2001-09-14",
    "id": "75102-3055",
    "libelle_voie_complet": "RUE DUSSOUBS",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 3392,
    "cle_rivoli": "H",
    "libelle_voie": "ETIENNE MARCEL",
    "voie_privee": false,
    "code_majic": "00055",
    "mot_directeur": "MARCEL",
    "date_ajout": "2001-09-14",
    "id": "75102-3392",
    "libelle_voie_complet": "RUE ETIENNE MARCEL",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 3534,
    "cle_rivoli": "M",
    "libelle_voie": "FAVART",
    "voie_privee": false,
    "code_majic": "00056",
    "mot_directeur": "FAVART",
    "date_ajout": "2001-09-14",
    "id": "75102-3534",
    "libelle_voie_complet": "RUE FAVART",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 3634,
    "cle_rivoli": "W",
    "libelle_voie": "FEYDEAU",
    "voie_privee": false,
    "code_majic": "00057",
    "mot_directeur": "FEYDEAU",
    "date_ajout": "2001-09-14",
    "id": "75102-3634",
    "libelle_voie_complet": "GALERIE FEYDEAU",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 3635,
    "cle_rivoli": "X",
    "libelle_voie": "FEYDEAU",
    "voie_privee": false,
    "code_majic": "00058",
    "mot_directeur": "FEYDEAU",
    "date_ajout": "2001-09-14",
    "id": "75102-3635",
    "libelle_voie_complet": "RUE FEYDEAU",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 3645,
    "cle_rivoli": "H",
    "libelle_voie": "DES FILLES SAINT THOMAS",
    "voie_privee": false,
    "code_majic": "00059",
    "mot_directeur": "THOMAS",
    "date_ajout": "2001-09-14",
    "id": "75102-3645",
    "libelle_voie_complet": "RUE DES FILLES SAINT THOMAS",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 3739,
    "cle_rivoli": "K",
    "libelle_voie": "DES FORGES",
    "voie_privee": false,
    "code_majic": "00060",
    "mot_directeur": "FORGES",
    "date_ajout": "2001-09-14",
    "id": "75102-3739",
    "libelle_voie_complet": "RUE DES FORGES",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 3779,
    "cle_rivoli": "D",
    "libelle_voie": "FRANCAISE",
    "voie_privee": false,
    "code_majic": "00061",
    "mot_directeur": "FRANCAIS",
    "date_ajout": "2001-09-14",
    "id": "75102-3779",
    "libelle_voie_complet": "RUE FRANCAISE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 3915,
    "cle_rivoli": "B",
    "libelle_voie": "GAILLON",
    "voie_privee": false,
    "code_majic": "00062",
    "mot_directeur": "GAILLON",
    "date_ajout": "2001-09-14",
    "id": "75102-3915",
    "libelle_voie_complet": "PLACE GAILLON",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 3916,
    "cle_rivoli": "C",
    "libelle_voie": "GAILLON",
    "voie_privee": false,
    "code_majic": "00063",
    "mot_directeur": "GAILLON",
    "date_ajout": "2001-09-14",
    "id": "75102-3916",
    "libelle_voie_complet": "RUE GAILLON",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 4227,
    "cle_rivoli": "R",
    "libelle_voie": "GOLDONI",
    "voie_privee": false,
    "code_majic": "00164",
    "mot_directeur": "GOLDONI",
    "date_ajout": "2001-09-14",
    "id": "75102-4227",
    "libelle_voie_complet": "PLACE GOLDONI",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 4265,
    "cle_rivoli": "G",
    "libelle_voie": "DE GRAMONT",
    "voie_privee": false,
    "code_majic": "00064",
    "mot_directeur": "GRAMONT",
    "date_ajout": "2001-09-14",
    "id": "75102-4265",
    "libelle_voie_complet": "RUE DE GRAMONT",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 4269,
    "cle_rivoli": "L",
    "libelle_voie": "DU GRAND CERF",
    "voie_privee": false,
    "code_majic": "00065",
    "mot_directeur": "CERF",
    "date_ajout": "2001-09-14",
    "id": "75102-4269",
    "libelle_voie_complet": "PASSAGE DU GRAND CERF",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 4317,
    "cle_rivoli": "N",
    "libelle_voie": "GRENETA",
    "voie_privee": false,
    "code_majic": "00066",
    "mot_directeur": "GRENETA",
    "date_ajout": "2001-09-14",
    "id": "75102-4317",
    "libelle_voie_complet": "COUR GRENETA",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 4318,
    "cle_rivoli": "P",
    "libelle_voie": "GRENETA",
    "voie_privee": false,
    "code_majic": "00067",
    "mot_directeur": "GRENETA",
    "date_ajout": "2001-09-14",
    "id": "75102-4318",
    "libelle_voie_complet": "RUE GRENETA",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 4328,
    "cle_rivoli": "A",
    "libelle_voie": "GRETRY",
    "voie_privee": false,
    "code_majic": "00068",
    "mot_directeur": "GRETRY",
    "date_ajout": "2001-09-14",
    "id": "75102-4328",
    "libelle_voie_complet": "RUE GRETRY",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 4374,
    "cle_rivoli": "A",
    "libelle_voie": "GUERIN BOISSEAU",
    "voie_privee": false,
    "code_majic": "00069",
    "mot_directeur": "BOISSEAU",
    "date_ajout": "2001-09-14",
    "id": "75102-4374",
    "libelle_voie_complet": "RUE GUERIN BOISSEAU",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 4467,
    "cle_rivoli": "B",
    "libelle_voie": "DE HANOVRE",
    "voie_privee": false,
    "code_majic": "00070",
    "mot_directeur": "HANOVRE",
    "date_ajout": "2001-09-14",
    "id": "75102-4467",
    "libelle_voie_complet": "RUE DE HANOVRE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 4593,
    "cle_rivoli": "N",
    "libelle_voie": "HENRI SALVADOR",
    "voie_privee": false,
    "code_majic": "00166",
    "mot_directeur": "SALVADOR",
    "date_ajout": "2015-05-26",
    "id": "75102-4593",
    "libelle_voie_complet": "PLACE HENRI SALVADOR",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 4758,
    "cle_rivoli": "T",
    "libelle_voie": "DES ITALIENS",
    "voie_privee": false,
    "code_majic": "00071",
    "mot_directeur": "ITALIENS",
    "date_ajout": "2001-09-14",
    "id": "75102-4758",
    "libelle_voie_complet": "BOULEVARD DES ITALIENS",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 4779,
    "cle_rivoli": "R",
    "libelle_voie": "JACQUES BIDAUT",
    "voie_privee": false,
    "code_majic": "00072",
    "mot_directeur": "BIDAUT",
    "date_ajout": "2001-09-14",
    "id": "75102-4779",
    "libelle_voie_complet": "SQUARE JACQUES BIDAUT",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 4973,
    "cle_rivoli": "B",
    "libelle_voie": "DES JEUNEURS",
    "voie_privee": false,
    "code_majic": "00073",
    "mot_directeur": "JEUNEURS",
    "date_ajout": "2001-09-14",
    "id": "75102-4973",
    "libelle_voie_complet": "RUE DES JEUNEURS",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 5127,
    "cle_rivoli": "U",
    "libelle_voie": "DE LA JUSSIENNE",
    "voie_privee": false,
    "code_majic": "00074",
    "mot_directeur": "JUSSIENN",
    "date_ajout": "2001-09-14",
    "id": "75102-5127",
    "libelle_voie_complet": "RUE DE LA JUSSIENNE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 5244,
    "cle_rivoli": "W",
    "libelle_voie": "LA FEUILLADE",
    "voie_privee": false,
    "code_majic": "00075",
    "mot_directeur": "FEUILLAD",
    "date_ajout": "2001-09-14",
    "id": "75102-5244",
    "libelle_voie_complet": "RUE LA FEUILLADE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 5302,
    "cle_rivoli": "J",
    "libelle_voie": "DE LA MICHODIERE",
    "voie_privee": false,
    "code_majic": "00076",
    "mot_directeur": "MICHODIE",
    "date_ajout": "2001-09-14",
    "id": "75102-5302",
    "libelle_voie_complet": "RUE DE LA MICHODIERE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 5507,
    "cle_rivoli": "G",
    "libelle_voie": "LEMOINE",
    "voie_privee": false,
    "code_majic": "00077",
    "mot_directeur": "LEMOINE",
    "date_ajout": "2001-09-14",
    "id": "75102-5507",
    "libelle_voie_complet": "PASSAGE LEMOINE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 5536,
    "cle_rivoli": "N",
    "libelle_voie": "LEON CLADEL",
    "voie_privee": false,
    "code_majic": "00078",
    "mot_directeur": "CLADEL",
    "date_ajout": "2001-09-14",
    "id": "75102-5536",
    "libelle_voie_complet": "RUE LEON CLADEL",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 5582,
    "cle_rivoli": "N",
    "libelle_voie": "LEOPOLD BELLAN",
    "voie_privee": false,
    "code_majic": "00079",
    "mot_directeur": "BELLAN",
    "date_ajout": "2001-09-14",
    "id": "75102-5582",
    "libelle_voie_complet": "RUE LEOPOLD BELLAN",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 5792,
    "cle_rivoli": "S",
    "libelle_voie": "LOUIS-LE-GRAND",
    "voie_privee": false,
    "code_majic": "00080",
    "mot_directeur": "GRAND",
    "date_ajout": "2001-09-14",
    "id": "75102-5792",
    "libelle_voie_complet": "RUE LOUIS LE GRAND",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 5820,
    "cle_rivoli": "X",
    "libelle_voie": "DE LOUVOIS",
    "voie_privee": false,
    "code_majic": "00081",
    "mot_directeur": "LOUVOIS",
    "date_ajout": "2001-09-14",
    "id": "75102-5820",
    "libelle_voie_complet": "RUE DE LOUVOIS",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 5821,
    "cle_rivoli": "Y",
    "libelle_voie": "LOUVOIS",
    "voie_privee": false,
    "code_majic": "00082",
    "mot_directeur": "LOUVOIS",
    "date_ajout": "2001-09-14",
    "id": "75102-5821",
    "libelle_voie_complet": "SQUARE LOUVOIS",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 5825,
    "cle_rivoli": "C",
    "libelle_voie": "DU LOUVRE",
    "voie_privee": false,
    "code_majic": "00083",
    "mot_directeur": "LOUVRE",
    "date_ajout": "2001-09-14",
    "id": "75102-5825",
    "libelle_voie_complet": "RUE DU LOUVRE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 5846,
    "cle_rivoli": "A",
    "libelle_voie": "LULLI",
    "voie_privee": false,
    "code_majic": "00084",
    "mot_directeur": "LULLI",
    "date_ajout": "2001-09-14",
    "id": "75102-5846",
    "libelle_voie_complet": "RUE LULLI",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 5850,
    "cle_rivoli": "E",
    "libelle_voie": "DE LA LUNE",
    "voie_privee": false,
    "code_majic": "00085",
    "mot_directeur": "LUNE",
    "date_ajout": "2001-09-14",
    "id": "75102-5850",
    "libelle_voie_complet": "RUE DE LA LUNE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 5913,
    "cle_rivoli": "Y",
    "libelle_voie": "DU MAIL",
    "voie_privee": false,
    "code_majic": "00086",
    "mot_directeur": "MAIL",
    "date_ajout": "2001-09-14",
    "id": "75102-5913",
    "libelle_voie_complet": "RUE DU MAIL",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 5974,
    "cle_rivoli": "P",
    "libelle_voie": "MANDAR",
    "voie_privee": false,
    "code_majic": "00087",
    "mot_directeur": "MANDAR",
    "date_ajout": "2001-09-14",
    "id": "75102-5974",
    "libelle_voie_complet": "RUE MANDAR",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 6084,
    "cle_rivoli": "J",
    "libelle_voie": "MARIE STUART",
    "voie_privee": false,
    "code_majic": "00088",
    "mot_directeur": "STUART",
    "date_ajout": "2001-09-14",
    "id": "75102-6084",
    "libelle_voie_complet": "RUE MARIE STUART",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 6100,
    "cle_rivoli": "B",
    "libelle_voie": "DE MARIVAUX",
    "voie_privee": false,
    "code_majic": "00089",
    "mot_directeur": "MARIVAUX",
    "date_ajout": "2001-09-14",
    "id": "75102-6100",
    "libelle_voie_complet": "RUE DE MARIVAUX",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 6124,
    "cle_rivoli": "C",
    "libelle_voie": "MARSOLLIER",
    "voie_privee": false,
    "code_majic": "00090",
    "mot_directeur": "MARSOLLI",
    "date_ajout": "2001-09-14",
    "id": "75102-6124",
    "libelle_voie_complet": "RUE MARSOLLIER",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 6251,
    "cle_rivoli": "R",
    "libelle_voie": "MEHUL",
    "voie_privee": false,
    "code_majic": "00091",
    "mot_directeur": "MEHUL",
    "date_ajout": "2001-09-14",
    "id": "75102-6251",
    "libelle_voie_complet": "RUE MEHUL",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 6261,
    "cle_rivoli": "B",
    "libelle_voie": "MENARS",
    "voie_privee": false,
    "code_majic": "00092",
    "mot_directeur": "MENARS",
    "date_ajout": "2001-09-14",
    "id": "75102-6261",
    "libelle_voie_complet": "RUE MENARS",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 6298,
    "cle_rivoli": "S",
    "libelle_voie": "METRO MONTMARTRE",
    "voie_privee": false,
    "code_majic": "00093",
    "mot_directeur": "MONTMART",
    "date_ajout": "2001-09-14",
    "id": "75102-6298",
    "libelle_voie_complet": "VOIE COMMUNALE METRO MONTMARTRE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 6446,
    "cle_rivoli": "C",
    "libelle_voie": "MONSIGNY",
    "voie_privee": false,
    "code_majic": "00094",
    "mot_directeur": "MONSIGNY",
    "date_ajout": "2001-09-14",
    "id": "75102-6446",
    "libelle_voie_complet": "RUE MONSIGNY",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 6510,
    "cle_rivoli": "X",
    "libelle_voie": "MONTMARTRE",
    "voie_privee": false,
    "code_majic": "00095",
    "mot_directeur": "MONTMART",
    "date_ajout": "2001-09-14",
    "id": "75102-6510",
    "libelle_voie_complet": "BOULEVARD MONTMARTRE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 6511,
    "cle_rivoli": "Y",
    "libelle_voie": "MONTMARTRE",
    "voie_privee": false,
    "code_majic": "00096",
    "mot_directeur": "MONTMART",
    "date_ajout": "2001-09-14",
    "id": "75102-6511",
    "libelle_voie_complet": "CITE MONTMARTRE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 6512,
    "cle_rivoli": "Z",
    "libelle_voie": "MONTMARTRE",
    "voie_privee": false,
    "code_majic": "00097",
    "mot_directeur": "MONTMART",
    "date_ajout": "2001-09-14",
    "id": "75102-6512",
    "libelle_voie_complet": "GALERIE MONTMARTRE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 6513,
    "cle_rivoli": "A",
    "libelle_voie": "MONTMARTRE",
    "voie_privee": false,
    "code_majic": "00098",
    "mot_directeur": "MONTMART",
    "date_ajout": "2001-09-14",
    "id": "75102-6513",
    "libelle_voie_complet": "RUE MONTMARTRE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 6520,
    "cle_rivoli": "H",
    "libelle_voie": "MONTORGUEIL",
    "voie_privee": false,
    "code_majic": "00099",
    "mot_directeur": "MONTORGU",
    "date_ajout": "2001-09-14",
    "id": "75102-6520",
    "libelle_voie_complet": "RUE MONTORGUEIL",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 6635,
    "cle_rivoli": "H",
    "libelle_voie": "DE MULHOUSE",
    "voie_privee": false,
    "code_majic": "00100",
    "mot_directeur": "MULHOUSE",
    "date_ajout": "2001-09-14",
    "id": "75102-6635",
    "libelle_voie_complet": "RUE DE MULHOUSE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 6783,
    "cle_rivoli": "U",
    "libelle_voie": "DU NIL",
    "voie_privee": false,
    "code_majic": "00101",
    "mot_directeur": "NIL",
    "date_ajout": "2001-09-14",
    "id": "75102-6783",
    "libelle_voie_complet": "RUE DU NIL",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 6828,
    "cle_rivoli": "T",
    "libelle_voie": "N-D DE BONNE NOUVELLE",
    "voie_privee": false,
    "code_majic": "00102",
    "mot_directeur": "NOUVELLE",
    "date_ajout": "2001-09-14",
    "id": "75102-6828",
    "libelle_voie_complet": "RUE ND DE BONNE NOUVELLE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 6836,
    "cle_rivoli": "B",
    "libelle_voie": "NOTRE-DAME DE RECOUVRANCE",
    "voie_privee": false,
    "code_majic": "00103",
    "mot_directeur": "RECOUVRA",
    "date_ajout": "2001-09-14",
    "id": "75102-6836",
    "libelle_voie_complet": "RUE NOTRE DAME DE RECOUVRANCE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 6840,
    "cle_rivoli": "F",
    "libelle_voie": "NOTRE-DAME DES VICTOIRES",
    "voie_privee": false,
    "code_majic": "00104",
    "mot_directeur": "VICTOIRE",
    "date_ajout": "2001-09-14",
    "id": "75102-6840",
    "libelle_voie_complet": "RUE NOTRE DAME DES VICTOIRES",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 6904,
    "cle_rivoli": "A",
    "libelle_voie": "DE L OPERA",
    "voie_privee": false,
    "code_majic": "00105",
    "mot_directeur": "OPERA",
    "date_ajout": "2001-09-14",
    "id": "75102-6904",
    "libelle_voie_complet": "AVENUE DE L OPERA",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 6905,
    "cle_rivoli": "B",
    "libelle_voie": "DE L OPERA",
    "voie_privee": false,
    "code_majic": "00106",
    "mot_directeur": "OPERA",
    "date_ajout": "2001-09-14",
    "id": "75102-6905",
    "libelle_voie_complet": "PLACE DE L OPERA",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 6998,
    "cle_rivoli": "C",
    "libelle_voie": "DE LA PAIX",
    "voie_privee": false,
    "code_majic": "00107",
    "mot_directeur": "PAIX",
    "date_ajout": "2001-09-14",
    "id": "75102-6998",
    "libelle_voie_complet": "RUE DE LA PAIX",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 7018,
    "cle_rivoli": "Z",
    "libelle_voie": "DE PALESTRO",
    "voie_privee": false,
    "code_majic": "00108",
    "mot_directeur": "PALESTRO",
    "date_ajout": "2001-09-14",
    "id": "75102-7018",
    "libelle_voie_complet": "RUE DE PALESTRO",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 7028,
    "cle_rivoli": "K",
    "libelle_voie": "DES PANORAMAS",
    "voie_privee": false,
    "code_majic": "00109",
    "mot_directeur": "PANORAMA",
    "date_ajout": "2001-09-14",
    "id": "75102-7028",
    "libelle_voie_complet": "PASSAGE DES PANORAMAS",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 7029,
    "cle_rivoli": "L",
    "libelle_voie": "DES PANORAMAS",
    "voie_privee": false,
    "code_majic": "00110",
    "mot_directeur": "PANORAMA",
    "date_ajout": "2001-09-14",
    "id": "75102-7029",
    "libelle_voie_complet": "RUE DES PANORAMAS",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 7167,
    "cle_rivoli": "L",
    "libelle_voie": "PAUL LELONG",
    "voie_privee": false,
    "code_majic": "00111",
    "mot_directeur": "LELONG",
    "date_ajout": "2001-09-14",
    "id": "75102-7167",
    "libelle_voie_complet": "RUE PAUL LELONG",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 7218,
    "cle_rivoli": "S",
    "libelle_voie": "DES PEINTRES",
    "voie_privee": false,
    "code_majic": "00112",
    "mot_directeur": "PEINTRES",
    "date_ajout": "2001-09-14",
    "id": "75102-7218",
    "libelle_voie_complet": "IMPASSE DES PEINTRES",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 7346,
    "cle_rivoli": "F",
    "libelle_voie": "DES PETITS CARREAUX",
    "voie_privee": false,
    "code_majic": "00113",
    "mot_directeur": "CARREAUX",
    "date_ajout": "2001-09-14",
    "id": "75102-7346",
    "libelle_voie_complet": "RUE DES PETITS CARREAUX",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 7348,
    "cle_rivoli": "H",
    "libelle_voie": "DES PETITS CHAMPS",
    "voie_privee": false,
    "code_majic": "00114",
    "mot_directeur": "CHAMPS",
    "date_ajout": "2001-09-14",
    "id": "75102-7348",
    "libelle_voie_complet": "RUE DES PETITS CHAMPS",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 7352,
    "cle_rivoli": "M",
    "libelle_voie": "DES PETITS PERES",
    "voie_privee": false,
    "code_majic": "00115",
    "mot_directeur": "PERES",
    "date_ajout": "2001-09-14",
    "id": "75102-7352",
    "libelle_voie_complet": "PASSAGE DES PETITS PERES",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 7353,
    "cle_rivoli": "N",
    "libelle_voie": "DES PETITS PERES",
    "voie_privee": false,
    "code_majic": "00116",
    "mot_directeur": "PERES",
    "date_ajout": "2001-09-14",
    "id": "75102-7353",
    "libelle_voie_complet": "PLACE DES PETITS PERES",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 7354,
    "cle_rivoli": "P",
    "libelle_voie": "DES PETITS PERES",
    "voie_privee": false,
    "code_majic": "00117",
    "mot_directeur": "PERES",
    "date_ajout": "2001-09-14",
    "id": "75102-7354",
    "libelle_voie_complet": "RUE DES PETITS PERES",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 7446,
    "cle_rivoli": "P",
    "libelle_voie": "PIERRE LAZAREFF",
    "voie_privee": false,
    "code_majic": "00165",
    "mot_directeur": "LAZAREFF",
    "date_ajout": "2001-09-14",
    "id": "75102-7446",
    "libelle_voie_complet": "ALLEE PIERRE LAZAREFF",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 7458,
    "cle_rivoli": "C",
    "libelle_voie": "PIERRE LAZAREFF",
    "voie_privee": false,
    "code_majic": "00163",
    "mot_directeur": "LAZAREFF",
    "date_ajout": "2001-09-14",
    "id": "75102-7458",
    "libelle_voie_complet": "PLACE PIERRE LAZAREFF",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 7560,
    "cle_rivoli": "N",
    "libelle_voie": "POISSONNIERE",
    "voie_privee": false,
    "code_majic": "00118",
    "mot_directeur": "POISSONN",
    "date_ajout": "2001-09-14",
    "id": "75102-7560",
    "libelle_voie_complet": "BOULEVARD POISSONNIERE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 7561,
    "cle_rivoli": "P",
    "libelle_voie": "POISSONNIERE",
    "voie_privee": false,
    "code_majic": "00119",
    "mot_directeur": "POISSONN",
    "date_ajout": "2001-09-14",
    "id": "75102-7561",
    "libelle_voie_complet": "RUE POISSONNIERE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 7589,
    "cle_rivoli": "V",
    "libelle_voie": "DU PONCEAU",
    "voie_privee": false,
    "code_majic": "00120",
    "mot_directeur": "PONCEAU",
    "date_ajout": "2001-09-14",
    "id": "75102-7589",
    "libelle_voie_complet": "PASSAGE DU PONCEAU",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 7590,
    "cle_rivoli": "W",
    "libelle_voie": "DU PONCEAU",
    "voie_privee": false,
    "code_majic": "00121",
    "mot_directeur": "PONCEAU",
    "date_ajout": "2001-09-14",
    "id": "75102-7590",
    "libelle_voie_complet": "RUE DU PONCEAU",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 7738,
    "cle_rivoli": "G",
    "libelle_voie": "DE PORT MAHON",
    "voie_privee": false,
    "code_majic": "00122",
    "mot_directeur": "MAHON",
    "date_ajout": "2001-09-14",
    "id": "75102-7738",
    "libelle_voie_complet": "RUE DE PORT MAHON",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 7835,
    "cle_rivoli": "M",
    "libelle_voie": "DES PRINCES",
    "voie_privee": false,
    "code_majic": "00123",
    "mot_directeur": "PRINCES",
    "date_ajout": "2001-09-14",
    "id": "75102-7835",
    "libelle_voie_complet": "PASSAGE DES PRINCES",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 7930,
    "cle_rivoli": "R",
    "libelle_voie": "DU QUATRE SEPTEMBRE",
    "voie_privee": false,
    "code_majic": "00124",
    "mot_directeur": "SEPTEMBR",
    "date_ajout": "2001-09-14",
    "id": "75102-7930",
    "libelle_voie_complet": "RUE DU QUATRE SEPTEMBRE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 8011,
    "cle_rivoli": "D",
    "libelle_voie": "RAMEAU",
    "voie_privee": false,
    "code_majic": "00125",
    "mot_directeur": "RAMEAU",
    "date_ajout": "2001-09-14",
    "id": "75102-8011",
    "libelle_voie_complet": "RUE RAMEAU",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 8073,
    "cle_rivoli": "W",
    "libelle_voie": "REAUMUR",
    "voie_privee": false,
    "code_majic": "00126",
    "mot_directeur": "REAUMUR",
    "date_ajout": "2001-09-14",
    "id": "75102-8073",
    "libelle_voie_complet": "RUE REAUMUR",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 8212,
    "cle_rivoli": "X",
    "libelle_voie": "DE RICHELIEU",
    "voie_privee": false,
    "code_majic": "00127",
    "mot_directeur": "RICHELIE",
    "date_ajout": "2001-09-14",
    "id": "75102-8212",
    "libelle_voie_complet": "RUE DE RICHELIEU",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 8320,
    "cle_rivoli": "P",
    "libelle_voie": "DU ROI FRANCOIS",
    "voie_privee": false,
    "code_majic": "00128",
    "mot_directeur": "FRANCOIS",
    "date_ajout": "2001-09-14",
    "id": "75102-8320",
    "libelle_voie_complet": "COUR DU ROI FRANCOIS",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 8493,
    "cle_rivoli": "C",
    "libelle_voie": "SAINT AUGUSTIN",
    "voie_privee": false,
    "code_majic": "00129",
    "mot_directeur": "AUGUSTIN",
    "date_ajout": "2001-09-14",
    "id": "75102-8493",
    "libelle_voie_complet": "RUE SAINT AUGUSTIN",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 8522,
    "cle_rivoli": "J",
    "libelle_voie": "SAINT DENIS",
    "voie_privee": false,
    "code_majic": "00130",
    "mot_directeur": "DENIS",
    "date_ajout": "2001-09-14",
    "id": "75102-8522",
    "libelle_voie_complet": "BOULEVARD SAINT DENIS",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 8523,
    "cle_rivoli": "K",
    "libelle_voie": "SAINT DENIS",
    "voie_privee": false,
    "code_majic": "00131",
    "mot_directeur": "DENIS",
    "date_ajout": "2001-09-14",
    "id": "75102-8523",
    "libelle_voie_complet": "GALERIE SAINT DENIS",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 8524,
    "cle_rivoli": "L",
    "libelle_voie": "SAINT-DENIS",
    "voie_privee": false,
    "code_majic": "00132",
    "mot_directeur": "DENIS",
    "date_ajout": "2001-09-14",
    "id": "75102-8524",
    "libelle_voie_complet": "IMPASSE SAINT DENIS",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 8525,
    "cle_rivoli": "M",
    "libelle_voie": "SAINT-DENIS",
    "voie_privee": false,
    "code_majic": "00133",
    "mot_directeur": "DENIS",
    "date_ajout": "2001-09-14",
    "id": "75102-8525",
    "libelle_voie_complet": "RUE SAINT DENIS",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 8533,
    "cle_rivoli": "W",
    "libelle_voie": "SAINTE ANNE",
    "voie_privee": false,
    "code_majic": "00134",
    "mot_directeur": "ANNE",
    "date_ajout": "2001-09-14",
    "id": "75102-8533",
    "libelle_voie_complet": "PASSAGE SAINTE ANNE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 8534,
    "cle_rivoli": "X",
    "libelle_voie": "SAINTE-ANNE",
    "voie_privee": false,
    "code_majic": "00135",
    "mot_directeur": "ANNE",
    "date_ajout": "2001-09-14",
    "id": "75102-8534",
    "libelle_voie_complet": "RUE SAINTE ANNE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 8538,
    "cle_rivoli": "B",
    "libelle_voie": "SAINTE APOLLINE",
    "voie_privee": false,
    "code_majic": "00136",
    "mot_directeur": "APOLLINE",
    "date_ajout": "2001-09-14",
    "id": "75102-8538",
    "libelle_voie_complet": "RUE SAINTE APOLLINE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 8559,
    "cle_rivoli": "Z",
    "libelle_voie": "SAINTE FOY",
    "voie_privee": false,
    "code_majic": "00137",
    "mot_directeur": "FOY",
    "date_ajout": "2001-09-14",
    "id": "75102-8559",
    "libelle_voie_complet": "GALERIE SAINTE FOY",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 8560,
    "cle_rivoli": "A",
    "libelle_voie": "SAINTE FOY",
    "voie_privee": false,
    "code_majic": "00138",
    "mot_directeur": "FOY",
    "date_ajout": "2001-09-14",
    "id": "75102-8560",
    "libelle_voie_complet": "PASSAGE SAINTE FOY",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 8561,
    "cle_rivoli": "B",
    "libelle_voie": "SAINTE FOY",
    "voie_privee": false,
    "code_majic": "00139",
    "mot_directeur": "FOY",
    "date_ajout": "2001-09-14",
    "id": "75102-8561",
    "libelle_voie_complet": "RUE SAINTE FOY",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 8609,
    "cle_rivoli": "D",
    "libelle_voie": "SAINT FIACRE",
    "voie_privee": false,
    "code_majic": "00140",
    "mot_directeur": "FIACRE",
    "date_ajout": "2001-09-14",
    "id": "75102-8609",
    "libelle_voie_complet": "RUE SAINT FIACRE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 8659,
    "cle_rivoli": "H",
    "libelle_voie": "SAINT-JOSEPH",
    "voie_privee": false,
    "code_majic": "00141",
    "mot_directeur": "JOSEPH",
    "date_ajout": "2001-09-14",
    "id": "75102-8659",
    "libelle_voie_complet": "RUE SAINT JOSEPH",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 8685,
    "cle_rivoli": "L",
    "libelle_voie": "SAINT MARC",
    "voie_privee": false,
    "code_majic": "00142",
    "mot_directeur": "MARC",
    "date_ajout": "2001-09-14",
    "id": "75102-8685",
    "libelle_voie_complet": "GALERIE SAINT MARC",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 8686,
    "cle_rivoli": "M",
    "libelle_voie": "SAINT-MARC",
    "voie_privee": false,
    "code_majic": "00143",
    "mot_directeur": "MARC",
    "date_ajout": "2001-09-14",
    "id": "75102-8686",
    "libelle_voie_complet": "RUE SAINT MARC",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 8725,
    "cle_rivoli": "E",
    "libelle_voie": "SAINT-PHILIPPE",
    "voie_privee": false,
    "code_majic": "00144",
    "mot_directeur": "PHILIPPE",
    "date_ajout": "2001-09-14",
    "id": "75102-8725",
    "libelle_voie_complet": "RUE SAINT PHILIPPE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 8752,
    "cle_rivoli": "J",
    "libelle_voie": "SAINT-SAUVEUR",
    "voie_privee": false,
    "code_majic": "00145",
    "mot_directeur": "SAUVEUR",
    "date_ajout": "2001-09-14",
    "id": "75102-8752",
    "libelle_voie_complet": "RUE SAINT SAUVEUR",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 8769,
    "cle_rivoli": "C",
    "libelle_voie": "SAINT-SPIRE",
    "voie_privee": false,
    "code_majic": "00146",
    "mot_directeur": "SPIRE",
    "date_ajout": "2001-09-14",
    "id": "75102-8769",
    "libelle_voie_complet": "RUE SAINT SPIRE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 8894,
    "cle_rivoli": "N",
    "libelle_voie": "DE SEBASTOPOL",
    "voie_privee": false,
    "code_majic": "00147",
    "mot_directeur": "SEBASTOP",
    "date_ajout": "2001-09-14",
    "id": "75102-8894",
    "libelle_voie_complet": "BOULEVARD DE SEBASTOPOL",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 8922,
    "cle_rivoli": "U",
    "libelle_voie": "DU SENTIER",
    "voie_privee": false,
    "code_majic": "00148",
    "mot_directeur": "SENTIER",
    "date_ajout": "2001-09-14",
    "id": "75102-8922",
    "libelle_voie_complet": "RUE DU SENTIER",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 9293,
    "cle_rivoli": "X",
    "libelle_voie": "THOREL",
    "voie_privee": false,
    "code_majic": "00149",
    "mot_directeur": "THOREL",
    "date_ajout": "2001-09-14",
    "id": "75102-9293",
    "libelle_voie_complet": "RUE THOREL",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 9318,
    "cle_rivoli": "Z",
    "libelle_voie": "TIQUETONNE",
    "voie_privee": false,
    "code_majic": "00150",
    "mot_directeur": "TIQUETON",
    "date_ajout": "2001-09-14",
    "id": "75102-9318",
    "libelle_voie_complet": "RUE TIQUETONNE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 9408,
    "cle_rivoli": "X",
    "libelle_voie": "DE TRACY",
    "voie_privee": false,
    "code_majic": "00151",
    "mot_directeur": "TRACY",
    "date_ajout": "2001-09-14",
    "id": "75102-9408",
    "libelle_voie_complet": "RUE DE TRACY",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 9444,
    "cle_rivoli": "L",
    "libelle_voie": "DE LA TRINITE",
    "voie_privee": false,
    "code_majic": "00152",
    "mot_directeur": "TRINITE",
    "date_ajout": "2001-09-14",
    "id": "75102-9444",
    "libelle_voie_complet": "PASSAGE DE LA TRINITE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 9504,
    "cle_rivoli": "B",
    "libelle_voie": "DE TURBIGO",
    "voie_privee": false,
    "code_majic": "00153",
    "mot_directeur": "TURBIGO",
    "date_ajout": "2001-09-14",
    "id": "75102-9504",
    "libelle_voie_complet": "RUE DE TURBIGO",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 9535,
    "cle_rivoli": "K",
    "libelle_voie": "D UZES",
    "voie_privee": false,
    "code_majic": "00154",
    "mot_directeur": "UZES",
    "date_ajout": "2001-09-14",
    "id": "75102-9535",
    "libelle_voie_complet": "RUE D UZES",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 9601,
    "cle_rivoli": "G",
    "libelle_voie": "DES VARIETES",
    "voie_privee": false,
    "code_majic": "00155",
    "mot_directeur": "VARIETES",
    "date_ajout": "2001-09-14",
    "id": "75102-9601",
    "libelle_voie_complet": "GALERIE DES VARIETES",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 9741,
    "cle_rivoli": "J",
    "libelle_voie": "DES VICTOIRES",
    "voie_privee": false,
    "code_majic": "00156",
    "mot_directeur": "VICTOIRE",
    "date_ajout": "2001-09-14",
    "id": "75102-9741",
    "libelle_voie_complet": "PLACE DES VICTOIRES",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 9779,
    "cle_rivoli": "A",
    "libelle_voie": "VIDE-GOUSSET",
    "voie_privee": false,
    "code_majic": "00157",
    "mot_directeur": "GOUSSET",
    "date_ajout": "2001-09-14",
    "id": "75102-9779",
    "libelle_voie_complet": "RUE VIDE GOUSSET",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 9834,
    "cle_rivoli": "K",
    "libelle_voie": "DE LA VILLE NEUVE",
    "voie_privee": false,
    "code_majic": "00158",
    "mot_directeur": "NEUVE",
    "date_ajout": "2001-09-14",
    "id": "75102-9834",
    "libelle_voie_complet": "RUE DE LA VILLE NEUVE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 9892,
    "cle_rivoli": "Y",
    "libelle_voie": "VIVIENNE",
    "voie_privee": false,
    "code_majic": "00159",
    "mot_directeur": "VIVIENNE",
    "date_ajout": "2001-09-14",
    "id": "75102-9892",
    "libelle_voie_complet": "GALERIE VIVIENNE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 9893,
    "cle_rivoli": "Z",
    "libelle_voie": "VIVIENNE",
    "voie_privee": false,
    "code_majic": "00160",
    "mot_directeur": "VIVIENNE",
    "date_ajout": "2001-09-14",
    "id": "75102-9893",
    "libelle_voie_complet": "RUE VIVIENNE",
    "lieu_dit_bati": ""
  },
  {
    "type": "voie",
    "code_type_voie": 1,
    "type_voie": "voie",
    "code_commune": 75102,
    "code_rivoli": 9900,
    "cle_rivoli": "G",
    "libelle_voie": "VOLNEY",
    "voie_privee": false,
    "code_majic": "00161",
    "mot_directeur": "VOLNEY",
    "date_ajout": "2001-09-14",
    "id": "75102-9900",
    "libelle_voie_complet": "RUE VOLNEY",
    "lieu_dit_bati": ""
  }
]

module.exports = adressesP2;